### PR TITLE
Mavenized project

### PR DESCRIPTION
**Pull request by pschichtel**
Quickly converted the project to a maven project and prepared it for maven central deployment.

### CODE REVIEW

**Comment by flanglet** [comment]
Could you set the version in the pom.xml to 1.4.0-SNAPSHOT and more importantly undelete build.xml (having support for maven is great but I still want to be able to build with ant) ?

**Comment by pschichtel** [comment]
Sure.

**Comment by pschichtel** [comment]
It was getting a little late yesterday, hence the short pr message. I checked the scripts you had around for building a android version. From what I've seen there are no Dependencies left that are not available on Android, so the scripts should be obsolete.
the pom is also prepared for maven central deployment, but before that a groupid must be registered at sonatype. Alternatively I could deploy it to a group ID I have access to.

**Comment by flanglet** [comment]
Yes, the Android scripts are obsolete. You can remove them or I'll do it
myself.

**Comment by pschichtel** [comment]
Rebased the branch, restored the build.xml and changed the version to 1.4.0-SNAPSHOT.

Last open question: What to do about the groupId ? Currently it's set to `tel.schich`.

**Comment by flanglet** [comment]
Hmmm. Not sure what to put in there. I do not want to have a reference to
another branch/repo in the master so maybe I'll just put 'flanglet',
Feel free to keep a different group ID in your clone it you want (but
you'll have to keep it in mind if/when you sync).
So change it or keep it and let me know when you are done.

On Sat, Feb 17, 2018 at 4:36 PM, Phillip Schichtel <notifications@github.com

**Comment by pschichtel** [comment]
The typical convention is to use a domain name you own in reverse, e.g. `com.flanglet` if you own that domain.

**Comment by flanglet** [comment]
I know. I have not registered any domain so far.

On Sat, Feb 17, 2018 at 6:37 PM, Phillip Schichtel <notifications@github.com

**Comment by pschichtel** [comment]
Ok, I've set it to `io.github.flanglet`.

The PR is ready now.

**Comment by flanglet** [comment]
Thanks. Merge is done.

**Pull request merged**
